### ISSUE TITLE
About occlusion_mask_from_photometric_error

### ISSUE THREAD

**Issue by SeokjuLee** [HalleyJiang/DiPE#1]
Hi Halley,

Thanks for sharing the project!
I have a minor question about the purpose of occlusion_mask_from_photometric_error in trainer.py.
In the code, you filter out the pixels where containing larger photometric errors than their minimum value.
Shouldn't it be the opposite?

**Comment by HalleyJiang** [comment]
This is actually the minimum reprojection loss in monodepth2. Please refer to the paper of monodepth2 to understand occlusion_mask_from_photometric_error.

**Comment by SeokjuLee** [comment]
Still, I cannot get the point of Eq. (11) in your paper. I understand the mechanism of auto-mask in Monodepth2, but for Eq. (11), which takes lower errors than the minimum reprojection error does not retain any pixels from the source view. Do I miss something?
